package com.somu.customized_exception_try_catch;

public class ControlflowInsideTryCatch {
	public static void main(String[] args) {
		
		try {
			System.out.println("Statement 1");
//			System.out.println(10/0);
			System.out.println("Statement 2");
//			System.out.println(10/0);
			System.out.println("Statement 3");
//			System.out.println(10/0);
		} catch (Exception e) {
			System.out.println("Statement 4");
//			System.out.println(10/0);
		}
		System.out.println("Statement 5");
		System.out.println("NORMAL TERMINATION");
	}
}
